version: '3.9'
services:
  mongodb:
    image: mongo:3.6.22-xenial
    ports:
      - "27017:27017"
    volumes: 
      - /data/db

  server:
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - mongodb
    ports:
      - '8000:8000'

  webapp:
    volumes:
       - ./:/usr/src/app
       - /usr/src/app/node_modules/
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - server
    ports:
      - '8080:8080'
