version: '3.9'
services:
  # mongodb:
  #   image: mongo:3.6.22-xenial
  #   ports:
  #     - "27017:27017"
  #   volumes: 
  #     - /data/db
  #     - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  #   environment:
  #     - MONGO_INITDB_DATABASE=talkieio

  dependencies:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/

  server:
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - dependencies
    ports:
      - '8000:8000'

  # webapp:
  #   volumes:
  #      - ./:/usr/src/app
  #      - /usr/src/app/node_modules/
  #   build:
  #     context: .
  #     dockerfile: frontend/Dockerfile
  #   depends_on:
  #     - server
  #   ports:
  #     - '8080:8080'
